// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSDvd-5q_5rbs-_8B2MZI4MRr_aLaxuo',
    appId: '1:47451053962:web:d7618d8736d6f6e77e3273',
    messagingSenderId: '47451053962',
    projectId: 'testsmashflutter',
    authDomain: 'testsmashflutter.firebaseapp.com',
    storageBucket: 'testsmashflutter.appspot.com',
    measurementId: 'G-4XW6D377HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCoGePuI1dxdLKmy4KegTOBKa0yJKocQ',
    appId: '1:47451053962:android:a2c031dbe582b2017e3273',
    messagingSenderId: '47451053962',
    projectId: 'testsmashflutter',
    storageBucket: 'testsmashflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqCtrEzTKVF9Cwaat90MrOUeNGz5OHlW4',
    appId: '1:47451053962:ios:3be74b37ca2bc0547e3273',
    messagingSenderId: '47451053962',
    projectId: 'testsmashflutter',
    storageBucket: 'testsmashflutter.appspot.com',
    iosClientId: '47451053962-shmuua8o5jphijgvf6929doviurmn10n.apps.googleusercontent.com',
    iosBundleId: 'com.lunch.testSmashFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqCtrEzTKVF9Cwaat90MrOUeNGz5OHlW4',
    appId: '1:47451053962:ios:de5e4bd6bbb928a37e3273',
    messagingSenderId: '47451053962',
    projectId: 'testsmashflutter',
    storageBucket: 'testsmashflutter.appspot.com',
    iosClientId: '47451053962-04drb70k05a78jj2h86gfpcb70f9nrva.apps.googleusercontent.com',
    iosBundleId: 'com.example.testSmashFlutter',
  );
}
