service: ${file(${opt:config-file}):service}
provider:
  name: aws
  endpointType: REGIONAL
  stage: ${opt:stage, 'local'}
  runtime: nodejs14.x
  region: sa-east-1
  versionFunctions: false
  deploymentBucket:
    name: serverless-example
  timeout: 30
  memorySize: 128
  vpc:
    securityGroupIds:
      #securityGroupIds
    subnetIds:
      #subnetIds
  environment: ${file(./config/env.${opt:stage}.yml)}

package:
  exclude:
    - "lib/phantomjs/phantomjs-linux"
    - "lib/phantomjs/phantomjs-mac"

functions: ${file(${opt:config-file}):functions}

custom:
  customDomain: ${file(${opt:config-file}):customDomain}
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-offline
  - serverless-domain-manager
